lafamilia/gestion/urls.py
from django.urls import path
from . import views
from pedidos.views import obtener_datos_iniciales
from .views import *

urlpatterns = [
    path('productos/', ProductoListView.as_view(), name='Productos'),
    path('productos/add/', ProductoCreateView.as_view(), name='Prod-Add'),
    path('productos/<int:pk>/edit/', ProductoUpdateView.as_view(), name='Prod-Edit'),  # Para editar productos
    path('productos/<int:pk>/delete/', ProductoDeleteView.as_view(), name='Prod-Delete'),  # Para eliminar productos
    path('vendedores/', VendedorListView.as_view(), name='Vendedores'),
    path('vendedores/add/', VendedorCreateView.as_view(), name='Vend-Add'),
    path('vendedores/<int:pk>/edit/', VendedorUpdateView.as_view(), name='Vend-Edit'),  # Para editar productos
    path('vendedores/<int:pk>/delete/', VendedorDeleteView.as_view(), name='Vend-Delete'),  # Para eliminar productos
    path('clientes/', ClienteListView.as_view(), name='Clientes'),
    path('clientes/add/', ClienteCreateView.as_view(), name='Cli-Add'),
    path('clientes/<int:pk>/edit/', ClienteUpdateView.as_view(), name='Cli-Edit'),  # Para editar productos
    path('clientes/<int:pk>/delete/', ClienteDeleteView.as_view(), name='Cli-Delete'),  # Para eliminar productos
    path('', lista_pedidos, name='lista_pedidos'),
    path('pedido/<int:pedido_id>/', ver_pedido, name='ver_pedido'),
    path('pedido/editar/<int:pedido_id>', agregar_productos_form, name='agregar_productos_form'),
    path('pedido/modificar/<int:pedido_id>/', actualizar_pedido, name='agregar_productos'),
    path('anular_pedido/<int:pedido_id>/', anular_pedido, name='anular_pedido'),
    path('pedido_especial/api/obtener-datos-iniciales/', obtener_datos_iniciales, name='obtener-datos-iniciales'),
    path('pedido_especial/', form_pedido_gestion, name='Ped-Form-Ges'),
    path('pedidos/imprimir/', views.pedidos_por_fecha, name='PedidosPorFecha'),
    path('pedidos/liquidacion/', views.pedidos_liquidacion, name='PedidosLiquidacion'),
]

lafamilia/lafamilia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.shortcuts import render

def custom_404(request, exception):
    return render(request, 'error/404.html', status=404)

handler404 = custom_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pedidos.urls')),
    path('gestion/', include('gestion.urls')),
    path('pedidos/', include('pedidos.urls'))
]

lafamilia/gestion/models.py
from django.db import models

class Producto(models.Model):
    marca=models.CharField(max_length=20, blank=True)
    nombre=models.CharField(max_length=20)
    descripcion=models.CharField(max_length=50, blank=True)
    precio=models.IntegerField()
    codigo=models.IntegerField(unique=True)
    stock=models.IntegerField()
    
    def __str__(self):
        return self.nombre

class Vendedor(models.Model):
    nombre=models.CharField(max_length=30)
    dni=models.IntegerField(unique=True, default=99999999)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=30)
    direccion = models.CharField(max_length=30)
    telefono = models.IntegerField(null=True)

    def __str__(self):
        return self.nombre


class Pedido(models.Model):
    DIAS_REPARTO = [
        ('Lunes', 'Lunes'),
        ('Miércoles', 'Miércoles'),
        ('Viernes', 'Viernes'),
        ('Sábado', 'Sábado'),
    ]
    
    fecha = models.DateTimeField(auto_now_add=True)
    modificado = models.BooleanField(default=False, blank=True, null=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, null=True)
    total = models.IntegerField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(Vendedor, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, through='PedidoProducto')
    diareparto = models.CharField(max_length=10, choices=DIAS_REPARTO, blank=True, null=True)
    observaciones = models.TextField(blank=True, null=True)
    anulado = models.BooleanField(blank=False, null=False, default=False)

    def __str__(self):
        return f"Pedido #{self.id} - {self.cliente.nombre}"


class PedidoProducto(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.IntegerField()
    agregado = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        unique_together = ('pedido', 'producto')

    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre} en Pedido #{self.pedido.id}"
    

lafamilia/gestion/forms.py
from django import forms
from .models import Producto, Vendedor, Cliente


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['marca', 'nombre', 'descripcion', 'precio', 'codigo', 'stock']

class VendedorForm(forms.ModelForm):
    class Meta:
        model = Vendedor
        fields = ['nombre', 'dni']

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'direccion', 'telefono']

lafamilia/gestion/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from .models import Producto, Vendedor, Cliente, Pedido, PedidoProducto
from .forms import ProductoForm, VendedorForm, ClienteForm
from django.http import JsonResponse, response
import json
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from datetime import datetime, timedelta
from django.contrib import messages

class ProductoListView(ListView):
    model = Producto
    template_name = 'gestion/prod.html'
    context_object_name = 'productos'

class ProductoCreateView(CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'gestion/prod-form.html'
    success_url = reverse_lazy('Productos')

class ProductoUpdateView(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'gestion/prod-form.html'
    success_url = reverse_lazy('Productos')

class ProductoDeleteView(DeleteView):
    model = Producto
    template_name = 'gestion/prod-delete.html'
    success_url = reverse_lazy('Productos')

class VendedorListView(ListView):
    model = Vendedor
    template_name = 'gestion/vend.html'
    context_object_name = 'vendedores'

class VendedorCreateView(CreateView):
    model = Vendedor
    form_class = VendedorForm
    template_name = 'gestion/vend-form.html'
    success_url = reverse_lazy('Vendedores')

class VendedorUpdateView(UpdateView):
    model = Vendedor
    form_class = VendedorForm
    template_name = 'gestion/vend-form.html'
    success_url = reverse_lazy('Vendedores')

class VendedorDeleteView(DeleteView):
    model = Vendedor
    template_name = 'gestion/vend-delete.html'
    success_url = reverse_lazy('Vendedores')

class ClienteListView(ListView):
    model = Cliente
    template_name = 'gestion/cli.html'
    context_object_name = 'clientes'

class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'gestion/cli-form.html'
    success_url = reverse_lazy('Clientes')

class ClienteUpdateView(UpdateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'gestion/cli-form.html'
    success_url = reverse_lazy('Clientes')

class ClienteDeleteView(DeleteView):
    model = Cliente
    template_name = 'gestion/cli-delete.html'
    success_url = reverse_lazy('Clientes')

def lista_pedidos(request):
    pedidos = Pedido.objects.all().order_by('-fecha')
    vendedores = Vendedor.objects.all()
    clientes = Cliente.objects.all()
    return render(request, 'gestion/ped.html', {'pedidos': pedidos, 'vendedores': vendedores, 'clientes': clientes})

def ver_pedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, id=pedido_id)
    productos_pedido = PedidoProducto.objects.filter(pedido=pedido)
    
    context = {
        'pedido': pedido,
        'productos_pedido': productos_pedido,
    }
    
    return render(request, 'gestion/ped-detalle.html', context)

def form_pedido_gestion(request):
    return render(request, 'gestion/ped-form.html')

def pedidos_por_fecha(request):
    # Obtener los datos del formulario
    fecha_inicio_str = request.GET.get('fecha_inicio')
    fecha_fin_str = request.GET.get('fecha_fin')
    vendedor_id = request.GET.get('vendedor')
    cliente_id = request.GET.get('cliente')
    diareparto = request.GET.get('diareparto')
    
    # Filtros básicos de fecha
    if fecha_inicio_str:
        fecha_inicio = timezone.make_aware(datetime.strptime(fecha_inicio_str, '%Y-%m-%d'))
    else:
        fecha_inicio = None
        
    if fecha_fin_str:
        fecha_fin = timezone.make_aware(datetime.strptime(fecha_fin_str, '%Y-%m-%d')) + timedelta(days=1) - timedelta(seconds=1)
    else:
        fecha_fin = None

    # Base de la consulta de pedidos
    pedidos = Pedido.objects.all()
    pedidos = pedidos.filter(anulado=False)
    
    # Filtrar por rango de fechas si las fechas están disponibles
    if fecha_inicio and fecha_fin:
        pedidos = pedidos.filter(fecha__range=[fecha_inicio, fecha_fin])
    elif fecha_inicio:
        pedidos = pedidos.filter(fecha__gte=fecha_inicio)
    elif fecha_fin:
        pedidos = pedidos.filter(fecha__lte=fecha_fin)

    # Filtro por vendedor
    if vendedor_id:
        pedidos = pedidos.filter(vendedor_id=vendedor_id)
    
    # Filtro por cliente
    if cliente_id:
        pedidos = pedidos.filter(cliente_id=cliente_id)
    
    # Filtro por día de reparto
    if diareparto:
        pedidos = pedidos.filter(diareparto=diareparto)
    
    # Renderizar la plantilla con los pedidos filtrados
    return render(request, 'gestion/ped-imprimir.html', {'pedidos': pedidos})

def pedidos_liquidacion(request):
    # Obtener los datos del formulario
    fecha_inicio_str = request.GET.get('fecha_inicio')
    fecha_fin_str = request.GET.get('fecha_fin')
    vendedor_id = request.GET.get('vendedor')
    cliente_id = request.GET.get('cliente')
    diareparto = request.GET.get('diareparto')
    
    # Filtros básicos de fecha
    if fecha_inicio_str:
        fecha_inicio = timezone.make_aware(datetime.strptime(fecha_inicio_str, '%Y-%m-%d'))
    else:
        fecha_inicio = None
        
    if fecha_fin_str:
        fecha_fin = timezone.make_aware(datetime.strptime(fecha_fin_str, '%Y-%m-%d')) + timedelta(days=1) - timedelta(seconds=1)
    else:
        fecha_fin = None

    # Base de la consulta de pedidos
    pedidos = Pedido.objects.all()
    pedidos = pedidos.filter(anulado=False)
    
    # Filtrar por rango de fechas si las fechas están disponibles
    if fecha_inicio and fecha_fin:
        pedidos = pedidos.filter(fecha__range=[fecha_inicio, fecha_fin])
    elif fecha_inicio:
        pedidos = pedidos.filter(fecha__gte=fecha_inicio)
    elif fecha_fin:
        pedidos = pedidos.filter(fecha__lte=fecha_fin)

    # Filtro por vendedor
    if vendedor_id:
        pedidos = pedidos.filter(vendedor_id=vendedor_id)
        vendedores = Vendedor.objects.filter(id=vendedor_id).values_list('nombre', flat=True)
    else:
        vendedores = Vendedor.objects.all().values_list('nombre', flat=True)
    
    # Filtro por cliente
    if cliente_id:
        pedidos = pedidos.filter(cliente_id=cliente_id)
    
    # Filtro por día de reparto
    if diareparto:
        pedidos = pedidos.filter(diareparto=diareparto)
    
    # Calcular el total de todos los pedidos filtrados
    total_pedidos = sum(pedido.total for pedido in pedidos)

    # Renderizar la plantilla con los pedidos filtrados, fechas, vendedores y total
    contexto = {
        'pedidos': pedidos,
        'fecha_inicio': fecha_inicio_str,
        'fecha_fin': fecha_fin_str,
        'vendedores': vendedores,
        'total_pedidos': total_pedidos,
    }

    return render(request, 'gestion/ped-liquidacion.html', contexto)


@csrf_exempt
def agregar_productos_form(request, pedido_id):
    # Obtener el pedido por su ID, o devolver un 404 si no existe
    pedido = get_object_or_404(Pedido, id=pedido_id)
    
    # Recoger los datos asociados al pedido
    cliente = pedido.cliente
    vendedor = pedido.vendedor
    fecha = pedido.fecha
    productos = Producto.objects.all()
    marcas = list(Producto.objects.values_list('marca', flat=True).distinct())

    # Pasar estos datos al template para renderizar
    context = {
        'pedido': pedido,
        'cliente': cliente,
        'vendedor': vendedor,
        'fecha': fecha,
        'productos': productos,
        'marcas': marcas
    }
    
    return render(request, 'gestion/ped-editar-form.html', context)

@csrf_exempt
def actualizar_pedido(request, pedido_id):
    if request.method == 'POST':
        data = json.loads(request.body)
        try:
            pedido = Pedido.objects.get(id=pedido_id)
            productos_data = data['productos']
            nuevo_total = data['total']  # Total calculado desde el frontend

            # Sumamos el nuevo total al total existente
            pedido.total += nuevo_total

            errores_stock = []
            
            # Recorrer cada producto enviado para la actualización
            for item in productos_data:
                producto = Producto.objects.get(id=item['producto_id'])
                cantidad = item['cantidad']
                precio_unitario = item['precio_unitario']

                # Verificar si el producto ya está en el pedido
                pedido_producto, creado = PedidoProducto.objects.get_or_create(
                    pedido=pedido,
                    producto=producto,
                    defaults={'cantidad': cantidad, 'precio_unitario': precio_unitario}
                )

                if creado:
                    # Si es un nuevo producto en el pedido, simplemente descontamos el stock
                    if producto.stock >= cantidad:
                        producto.stock -= cantidad
                        producto.save()
                    else:
                        errores_stock.append(f"{producto.nombre} - {producto.marca}. Disponible: {producto.stock}, solicitado: {cantidad}.")
                else:
                    # Si ya existe, actualizamos la cantidad y descontamos la nueva cantidad
                    cantidad_total = pedido_producto.cantidad + cantidad

                    if producto.stock >= cantidad:
                        producto.stock -= cantidad
                        producto.save()
                        pedido_producto.cantidad = cantidad_total
                        pedido_producto.precio_unitario = precio_unitario
                        pedido_producto.save()
                    else:
                        errores_stock.append(f"{producto.nombre} - {producto.marca}. Disponible: {producto.stock}, solicitado: {cantidad}.")
            
            # Si hay errores de stock, devolvemos los errores sin eliminar productos ya existentes
            if errores_stock:

lafamilia/templates/gestion/cli-delete.html
{% extends "gestion/index.html" %}
{% block content %}
<h1>Confirmar eliminación</h1>
<p>¿Estás seguro de que deseas eliminar al cliente "{{ object.nombre }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'Productos' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

lafamilia/templates/gestion/cli-form.html
{% extends 'gestion/index.html' %}
{% load static %}

{% block css %} <link rel="stylesheet" type="text/css" href={% static "css/form.css" %} /> {% endblock %}


{% block content %}
  <h2>Alta o modificacion de cliente</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

lafamilia/templates/gestion/cli.html
{% extends "gestion/index.html" %}

{% load static %}
{% block css %}
<!-- Agrega los estilos necesarios para los modales, si es necesario -->
{% endblock %}

{% block content %}
<h2>CLIENTES | Distribuidora La Familia</h2>
<HR></HR>

<div id="contenedor">
    <a class="btn btn-primary alta" href="{% url 'Cli-Add' %}" role="button">Alta de cliente</a>
    <table id="myTable" class="display">
        <thead>
        <tr>
            <th>ID</th>
            <th>Zona</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Teléfono</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            <tr>
                <td>{{ cliente.pk }}</td>
                <td>{{ cliente.zona }}</td>
                <td>{{ cliente.nombre }}</td>
                <td>{{ cliente.direccion }}</td>
                <td>{{ cliente.telefono }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'Cli-Edit' cliente.pk %}">Editar</a>
                    |
                    <a class="btn btn-danger" href="{% url 'Cli-Delete' cliente.pk %}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

{% endblock %}

lafamilia/templates/gestion/ped-editar-form.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificar pedido</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.5/css/dataTables.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href={% static "css/ped-form.css" %} />
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body>
    <div class="container">
        <h5>Editando pedido #<span id="pedidoid" value="{{ pedido.id }}">{{ pedido.id }}</span> del {{ pedido.fecha|date:"d/m/y" }} para {{ pedido.cliente }}
        </h5>
        <hr>
        <!-- Botones de Filtrado por Marca -->
         <h5>Seleccionar productos:</h5>
        <div class="btn-group-scroll" role="group" id="marca-buttons">
            <button type="button" class="btn btn-secondary" id="all-btn">Todas</button>
            {% for marca in marcas %}
                <button type="button" class="btn btn-secondary marca-btn" data-filter="{{ marca }}">{{ marca }}</button>
            {% endfor %}
        </div>

        <!-- Tabla de Productos -->
        <table id="productos-table" class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Precio</th>
                    <th>Agregar</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                    <tr data-marca="{{ producto.marca }}" data-prodid="{{ producto.id }}">
                        <td>{{ producto.nombre }}</td>
                        <td>{{ producto.marca }}</td>
                        <td>{{ producto.precio }}</td>
                        <td><button type="button" class="btn btn-success add-producto" data-id="{{ producto.id }}">+</button></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Lista de Productos en el Pedido -->
        <h3>Productos seleccionados:</h3>
        <table id="pedido-table" class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Cantidad</th>
                    <th>Precio unitario</th>
                    <th>Precio total</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <!-- Se llenará dinámicamente con jQuery -->
            </tbody>
        </table>
        <hr>
        <!-- Total del Pedido -->
        <h4>Total productos agregados: $<span id="total-pedido">0</span></h4>
        <button type="button" class="btn btn-primary" id="finalizar-pedido">Agregar productos</button>
        <button type="button" class="btn btn-danger" id="cancelar-pedido">Cancelar</button>
    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.5/js/dataTables.min.js"></script>
    <script type="text/javascript" src={% static "js/ped-editar-form.js" %}></script>
</body>
</html>

lafamilia/templates/gestion/ped-imprimir.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles de Pedidos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/ped-detalles.css' %}" />
</head>
<body>
    <img src={% static "img/lafam1.png" %} alt="Distribuidora La Familia" class="watermark">
    {% for pedido in pedidos %}
    <div class="pedido">
        <h4 style="text-align:center">Distribuidora La Familia - 2657 635398</h4>
        <hr>
        <H2 style="border-bottom:none; margin-bottom:5px; margin-top:25px">Detalles del Pedido #{{ pedido.id }}</H2>    
        <p><strong>Cliente:</strong> {{ pedido.cliente.nombre }}</p>
        <p><strong>Direccion:</strong> {{ pedido.cliente.direccion }}</p>
        <p><strong>Dia de reparto:</strong> {{ pedido.diareparto }}</p>
        <p><strong>Vendedor:</strong> {{ pedido.vendedor.nombre }}</p>
        <p><strong>Fecha:</strong> {{ pedido.fecha }}</p>
        <br>
        PRODUCTOS:
        <ul style="margin-bottom:28px; margin-top: 10px">
            {% for item in pedido.pedidoproducto_set.all %}
                <li>{{ item.producto.nombre }} - {{ item.producto.marca }} | Precio unitario: ${{ item.precio_unitario }} - Cantidad: {{ item.cantidad }} </li>
            {% endfor %}
        </ul>
        
        {% if pedido.observaciones %}
        <p>OBSERVACIONES: {{ pedido.observaciones }}</p>
        {% endif %}

        <h3>Total del Pedido: ${{ pedido.total }}</h3>
    </div>
    {% endfor %}
    
</body>
</html>

lafamilia/templates/gestion/ped-liquidacion.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href={% static "css/index.css" %} />
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
</head>
<body>
    <div id="contenedor">
        <h5>Pedidos del {{ fecha_inicio }} al {{ fecha_fin }} - Vendedor(es): 
            {% if vendedores %}
                {{ vendedores|join:", " }}
            {% else %}
                Todos los vendedores
            {% endif %}</h5>
        <hr>
        <table class="display" style="width:100%">
            <thead>
                <tr>
                    <th>ID Pedido</th>
                    <th>Cliente</th>
                    <th>Vendedor</th>
                    <th>Fecha</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                <tr>
                    <td>{{ pedido.id }}</td>
                    <td>{{ pedido.cliente.nombre }}</td>
                    <td>{{ pedido.vendedor.nombre }}</td>
                    <td>{{ pedido.fecha|date:"d/m/y H:i" }}</td>
                    <td>${{ pedido.total }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr>
        <h4 style="text-align: right; margin-right: 20px">Total: ${{ total_pedidos }}</h4>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>
</html>

lafamilia/templates/gestion/prod-delete.html
{% extends "gestion/index.html" %}
{% block content %}
<h1>Confirmar Eliminación</h1>
<p>¿Estás seguro de que deseas eliminar el producto "{{ object.nombre }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'Productos' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

lafamilia/templates/gestion/prod-form.html
{% extends 'gestion/index.html' %}
{% load static %}

{% block css %} <link rel="stylesheet" type="text/css" href={% static "css/form.css" %} /> {% endblock %}


{% block content %}
  <h2>Crear o modificar producto</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
{% endblock %}

lafamilia/templates/gestion/prod.html
{% extends "gestion/index.html" %}

{% load static %}
{% block css %}
<!-- Agrega los estilos necesarios para los modales, si es necesario -->
{% endblock %}

{% block content %}
<h2>PRODUCTOS | Distribuidora La Familia</h2>
<HR></HR>

<div id="contenedor">
    <a class="btn btn-primary alta" href="{% url 'Prod-Add' %}" role="button">Nuevo producto</a>
    <table id="myTable" class="display">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Precio</th>
            <th>Codigo</th>
            <th>Stock</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.marca }}</td>
                <td>{{ producto.precio }}</td>
                <td>{{ producto.codigo }}</td>
                <td>{{ producto.stock }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url 'Prod-Edit' producto.pk %}">Editar</a>
                    |
                    <a class="btn btn-danger" href="{% url 'Prod-Delete' producto.pk %}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
</script>

{% endblock %}